stages:
  - test
  - build
  - deploy

variables:
  IMAGE_TAG: aiprofilesmatchingacr.azurecr.io/aiprofilesmatching:latest
  AZURE_ACR: aiprofilesmatchingacr
  AZURE_WEBAPP: aiprofilesmatchingWebApp
  AZURE_RG: rg-cgi-weu-cloud-genAIshowcase-dev

.check_variables:
  before_script:
  - if [ -z "$AZURE_OPENAI_API_KEY" ] || [ -z "$AZURE_OPENAI_ENDPOINT" ] || [ -z "$AZURE_SEARCH_API_KEY" ] || [ -z "$AZURE_SEARCH_ENDPOINT" ] || [ -z "$AZURE_SP_ID" ] || [ -z "$AZURE_SP_SECRET" ] || [ -z "$AZURE_TENANT" ]; then echo "Une ou plusieurs variables d'environnement ne sont pas définies"; exit 1; fi

test:
  stage: test
  only:
    - dev_kevin
  image: python:3.11.9
  extends: .check_variables
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests

build:
  stage: build
  only:
    - dev_kevin
  image: trion/azure-cli:latest
  needs:
    - test
  extends: .check_variables
  script:
    - docker build --build-arg AZURE_OPENAI_API_KEY="$AZURE_OPENAI_API_KEY" --build-arg AZURE_OPENAI_ENDPOINT="$AZURE_OPENAI_ENDPOINT" --build-arg AZURE_SEARCH_API_KEY="$AZURE_SEARCH_API_KEY" --build-arg AZURE_SEARCH_ENDPOINT="$AZURE_SEARCH_ENDPOINT" -t $IMAGE_TAG .
    - az login --service-principal -u "$AZURE_SP_ID" -p "$AZURE_SP_SECRET" --tenant "$AZURE_TENANT"
    - az acr login --name $AZURE_ACR
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  only:
    - dev_kevin
  image: mcr.microsoft.com/azure-cli
  needs:
    - build
  extends: .check_variables
  script:
    - az login --service-principal -u "$AZURE_SP_ID" -p "$AZURE_SP_SECRET" --tenant "$AZURE_TENANT"
    - ACR_PASSWORD=$(az acr credential show --name $AZURE_ACR --query "passwords[0].value" -o tsv)
    - if [ -z "$ACR_PASSWORD" ]; then echo "Échec de la récupération du mot de passe ACR"; exit 1; fi
    - az webapp config container set --name $AZURE_WEBAPP --resource-group $AZURE_RG --docker-custom-image-name $IMAGE_TAG --docker-registry-server-url https://$AZURE_ACR.azurecr.io --docker-registry-server-user $AZURE_ACR --docker-registry-server-password $ACR_PASSWORD
    - az webapp restart --name $AZURE_WEBAPP --resource-group $AZURE_RG
