stages:
  - test
  - build
  - deploy

variables:
  IMAGE_TAG: aiprofilesmatchingacr.azurecr.io/aiprofilesmatching:latest
  AZURE_ACR: aiprofilesmatchingacr
  AZURE_WEBAPP: aiprofilesmatchingWebApp
  AZURE_RG: rg-cgi-weu-cloud-genAIshowcase-dev

test:
  stage: test
  only:
    - dev_kevin
  image: python:3.11.9
  before_script:
    - |
      # Vérifier que les variables d'environnement sont définies
      for var in AZURE_OPENAI_API_KEY AZURE_OPENAI_ENDPOINT AZURE_SEARCH_API_KEY AZURE_SEARCH_ENDPOINT AZURE_SP_ID AZURE_SP_SECRET AZURE_TENANT IMAGE_TAG; do
        if [ -z "${!var}" ]; then
          echo "La variable d'environnement $var n'est pas définie"
          exit 1
        fi
      done
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests

build:
  stage: build
  only:
    - dev_kevin
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  needs:
    - test
  before_script:
    - |
      # Vérifier que les variables d'environnement sont définies
      for var in AZURE_OPENAI_API_KEY AZURE_OPENAI_ENDPOINT AZURE_SEARCH_API_KEY AZURE_SEARCH_ENDPOINT AZURE_SP_ID AZURE_SP_SECRET AZURE_TENANT IMAGE_TAG; do
        if [ -z "${!var}" ]; then
          echo "La variable d'environnement $var n'est pas définie"
          exit 1
        fi
      done
  script:
    - docker build \
        --build-arg AZURE_OPENAI_API_KEY="$AZURE_OPENAI_API_KEY" \
        --build-arg AZURE_OPENAI_ENDPOINT="$AZURE_OPENAI_ENDPOINT" \
        --build-arg AZURE_SEARCH_API_KEY="$AZURE_SEARCH_API_KEY" \
        --build-arg AZURE_SEARCH_ENDPOINT="$AZURE_SEARCH_ENDPOINT" \
        -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  only:
    - dev_kevin
  image: mcr.microsoft.com/azure-cli
  needs:
    - build
  before_script:
    - |
      # Vérifier que les variables d'environnement sont définies
      for var in AZURE_OPENAI_API_KEY AZURE_OPENAI_ENDPOINT AZURE_SEARCH_API_KEY AZURE_SEARCH_ENDPOINT AZURE_SP_ID AZURE_SP_SECRET AZURE_TENANT IMAGE_TAG; do
        if [ -z "${!var}" ]; then
          echo "La variable d'environnement $var n'est pas définie"
          exit 1
        fi
      done
  script:
    - az login --service-principal \
        -u "$AZURE_SP_ID" \
        -p "$AZURE_SP_SECRET" \
        --tenant "$AZURE_TENANT"
    - ACR_PASSWORD=$(az acr credential show --name $AZURE_ACR --query "passwords[0].value" -o tsv)
    - |
      if [ -z "$ACR_PASSWORD" ]; then
        echo "Échec de la récupération du mot de passe ACR"
        exit 1
      fi
    - az webapp config container set \
        --name $AZURE_WEBAPP \
        --resource-group $AZURE_RG \
        --docker-custom-image-name $IMAGE_TAG \
        --docker-registry-server-url https://$AZURE_ACR.azurecr.io \
        --docker-registry-server-user $AZURE_ACR \
        --docker-registry-server-password $ACR_PASSWORD
    - az webapp restart \
        --name $AZURE_WEBAPP \
        --resource-group $AZURE_RG
