stages:
  - build
  - deploy

variables:
  REGISTRY_URL: aiprofilesmatchingacr.azurecr.io
  IMAGE_NAME: aiprofilesmatchingacr.azurecr.io/aiprofilesmatching_image
  AZURE_APP_NAME: aiprofilesmatchingWebApp
  AZURE_RESOURCE_GROUP: rg-cgi-weu-cloud-genAIshowcase-dev
  AZURE_OPENAI_API_KEY: $AZURE_OPENAI_API_KEY
  AZURE_OPENAI_ENDPOINT: $AZURE_OPENAI_ENDPOINT
  AZURE_SEARCH_API_KEY: $AZURE_SEARCH_API_KEY
  AZURE_SEARCH_ENDPOINT: $AZURE_SEARCH_ENDPOINT

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:dind
  only:
    - dev_kevin
  script:
    - echo "Building Docker image..."
    - docker build --build-arg AZURE_OPENAI_API_KEY="$AZURE_OPENAI_API_KEY" \
    --build-arg AZURE_OPENAI_ENDPOINT="$AZURE_OPENAI_ENDPOINT" \
    --build-arg AZURE_SEARCH_API_KEY="$AZURE_SEARCH_API_KEY" \
    --build-arg AZURE_SEARCH_ENDPOINT="$AZURE_SEARCH_ENDPOINT" \
    -t $IMAGE_NAME .

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:latest
  services:
    - docker:dind
  only:
    - dev_kevin
  script:
    - echo "Pushing image to Azure Container Registry..."
    - az acr login --name $REGISTRY_URL
    - docker push $IMAGE_NAME
    - echo "Deploying to Azure App Service..."
    - az webapp config container set --name $AZURE_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --docker-custom-image-name $IMAGE_NAME
