stages:
  - test
  - build
  - deploy

variables:
  IMAGE_TAG: aiprofilesmatchingacr.azurecr.io/aiprofilesmatching:latest
  AZURE_ACR: aiprofilesmatchingacr
  AZURE_WEBAPP: aiprofilesmatchingWebApp
  AZURE_RG: rg-cgi-weu-cloud-genAIshowcase-dev

# Définir un modèle vérifiant la présence des variables d'environnement
.check_env_vars:
  before_script:
    - chmod +x check_env_vars.sh
    - ./check_env_vars.sh

test:
  stage: test
  only:
    - dev_kevin
  image: python:3.11.9
  extends: .check_env_vars
  script:
    - set -e # Arrêter le script en cas d'erreur
    - pip install -r requirements.txt
    # Exécuter l'ensemble des tests unitaires
    - python -m unittest discover -s tests

build:
  stage: build
  only:
    - dev_kevin
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  needs:
    - test
  extends: .check_env_vars # Utiliser le modèle pour vérifier les variables d'environnement
  script:
    - set -e # Arrêter le script en cas d'erreur
    # Construire l'image Docker
    - docker build \
        --build-arg AZURE_OPENAI_API_KEY="$AZURE_OPENAI_API_KEY" \
        --build-arg AZURE_OPENAI_ENDPOINT="$AZURE_OPENAI_ENDPOINT" \
        --build-arg AZURE_SEARCH_API_KEY="$AZURE_SEARCH_API_KEY" \
        --build-arg AZURE_SEARCH_ENDPOINT="$AZURE_SEARCH_ENDPOINT" \
        -t $IMAGE_TAG .
    # Push de l'image dans le registre Azure Container Registry
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  only:
    - dev_kevin
  image: mcr.microsoft.com/azure-cli
  needs:
    - build
  extends: .check_env_vars # Utiliser le modèle pour vérifier les variables d'environnement
  script:
    - set -e # Arrêter le script en cas d'erreur
    # Se connecter à Azure
    - az login --service-principal \
        -u "$AZURE_SP_ID" \
        -p "$AZURE_SP_SECRET" \
        --tenant "$AZURE_TENANT"
    # Récupérer le mot de passe de l'ACR
    - ACR_PASSWORD=$(az acr credential show --name $AZURE_ACR --query "passwords[0].value" -o tsv)
    # Vérifier que le mot de passe a bien été récupéré
    - if [ -z "$ACR_PASSWORD" ]; then \
        echo "Échec de la récupération du mot de passe ACR"; exit 1; fi
    # Mettre à jour le conteneur de l'application web
    - az webapp config container set \
        --name $AZURE_WEBAPP \
        --resource-group $AZURE_RG \
        --docker-custom-image-name $IMAGE_TAG \
        --docker-registry-server-url https://$AZURE_ACR.azurecr.io \
        --docker-registry-server-user $AZURE_ACR \
        --docker-registry-server-password $ACR_PASSWORD
    # Redémarrer l'application web
    - az webapp restart \
        --name $AZURE_WEBAPP \
        --resource-group $AZURE_RG
